---
namespace: "entropia"
name: "sso"
version: "0.0.2"
readme: "README.md"
license_file: "LICENSE"
authors:
    - "promasu <git@promasu.tech>"
    - "transcaffeine <transcaffeine@finally.coffee>"
tags:
    - sso
    - keycloak
    - collection
repository: "https://github.com/entropia/ansible-collection-sso"
