FROM {{ keycloak_container_upstream_image_name }}:{{ keycloak_version }} as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED={{ keycloak_config_health_enabled | ternary('true', 'false') }}
ENV KC_METRICS_ENABLED={{ keycloak_config_metrics_enabled | ternary('true', 'false') }}

# Configure a database vendor
ARG DB_VENDOR
ENV KC_DB=$DB_VENDOR

WORKDIR {{ keycloak_container_working_directory }}
RUN {{ keycloak_container_working_directory }}/bin/kc.sh build


FROM {{ keycloak_container_upstream_image_name }}:{{ keycloak_version }}
COPY --from=builder {{ keycloak_container_working_directory }}/ {{ keycloak_container_working_directory }}/

ENV KC_HOSTNAME={{ keycloak_config_hostname }}
ENV KEYCLOAK_ADMIN={{ keycloak_config_admin_username }}
ARG KC_ADMIN_PASSWORD
ENV KEYCLOAK_PASSWORD=$KC_ADMIN_PASSWORD
ENTRYPOINT ["{{ keycloak_container_working_directory }}/bin/kc.sh"]
